# -*- coding: utf-8 -*-
"""assignment 1 py bootcamp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2JYzAs4YUQNlk_DZMbpD11UQY73_lDo
"""

1.
#a1
Name = "meghowal"
print(type(Name))

#a2
Age = 21
print(type(Age))

#a3
Gpa = 4.01
print(type(Gpa))

#a4
is_student = True
print(type(is_student))

#1.b
#b1
string = "123"
stringint = int(string)
print(stringint)

#b2
num = 456
numstring = str(num)
print(numstring)


#b3
something = 3.99
somethingint = int(something)
print(somethingint)
#it performs truncation, which means it simply discards the decimal part of the number,

#b4
one = bool (1)
zero = bool (0)
print(one)
print(zero)

a=17
b=5
print(f"Addition: {a} + {b} = {a + b}")
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

# Declare the numbers
num1 = 17
num2 = 5

# Basic Arithmetic
print(f"Addition: {num1} + {num2} = {num1 + num2}")
print(f"Subtraction: {num1} - {num2} = {num1 - num2}")
print(f"Multiplication: {num1} * {num2} = {num1 * num2}")
print(f"Division: {num1} / {num2} = {num1 / num2}")

# Floor Division and Modulus
print(f"Floor Division : {num1 // num2}")
print(f"Modulus : {num1 % num2}")

# Exponentiation (Power)
print(f"Exponentiation: {num1 ** num2}")

# Comparison Results
print(f"Is 17 > 5? {num1 > num2}")
print(f"Is 17 == 5? {num1 == num2}")
print(f"Is 17 != 5? {num1 != num2}")

#q3a
name = "python programming"
print(name.upper())
print(name.title())
print(name.replace("programming" , "language"))
print(len(name))

#q3b
name = "meghowal"
age = 21
gpa = 4.00
print(f"My name is {name}, I am {age} years old, and my GPA is {gpa}.")

#q4
age = int(input("Enter your age: "))
if age >= 18 :
    print("you are adult")
elif age < 13 and age > -1:
    print ("tumi bacha")
elif age >= 13 and age <= 17:
    print("Teenager")
else :
    print ("invalid input")

#q4b
#Even / Odd using a ternary operator in a single line:

number = int(input("Enter a number:"))
if number%2 == 0:
  print (f"{number} is even")

else :
  print(f" {number} is odd")

#q4c
#Grade Calculator — take a student's mark (0–100) as input:
mark = int(input("Enter your mark: "))
if mark >= 90 and mark <= 100:
    print("Grade: A+")
elif mark >= 80 and mark <= 89:
    print("Grade: A")
elif mark >= 70 and mark <= 79:
    print("Grade: B")
elif mark >= 60 and mark <= 69:
    print("Grade: C")
elif mark >= 50 and mark <= 59:
    print("Grade: D")
elif mark >= 0 and mark <= 49:
    print("Grade: F")
else:
    print("Invalid input")

#q4b
#Login System — simulate a simple login:

username = "mustakim"
password = "1234"

attempts = 0
max_attempts = 3

while attempts < max_attempts:
  input_username = input("Enter your username: ")
  input_password = input("Enter your password:")

  if input_username == username and input_password == password:
    print("lo#gin successful")
    break
  elif input_username == username and input_password != password:
    print("Invalid password")
  elif input_username != username and input_password == password:
    print("user not found")
  else:
    print("Invalid attempt")

  attempts += 1
  if attempts == max_attempts:
    print(f"You have exceeded the maximum of {max_attempts} login attempts. Account locked.")

#Q5A

PIN_NUMBER = "1234"
balance = 1000
INPUT_PIN = input("Enter your PIN: ")
if INPUT_PIN == PIN_NUMBER:
    print("PIN accepted. Welcome!")
    input_withdraw_amount = int(input("Enter the amount to withdraw: "))
    if input_withdraw_amount <= balance and input_withdraw_amount > 500:
        balance -= input_withdraw_amount
        print(f"Withdrawal successful. Remaining balance: {balance}")
    elif input_withdraw_amount > balance:
        print("Insufficient balance")
    elif input_withdraw_amount <= 500:
        print("Minimum withdrawal amount is greater than 500")
elif INPUT_PIN != PIN_NUMBER:
    print("pin not correct")

#Q5B

PIN_NUMBER = "1234"
balance = 1000
attemps = 0
maximumatemps = 3

while attemps < maximumatemps:
    INPUT_PIN = input("Enter your PIN: ")
    if INPUT_PIN == PIN_NUMBER:
        print("PIN accepted. Welcome!")

        input_withdraw_amount = int(input("Enter the amount to withdraw: "))
        if input_withdraw_amount <= balance and input_withdraw_amount > 500:
            balance -= input_withdraw_amount
            print(f"Withdrawal successful. Remaining balance: {balance}")
        elif input_withdraw_amount > balance:
            print("Insufficient balance")
        elif input_withdraw_amount <= 500:
            print("Minimum withdrawal amount is greater than 500")
        break

    else:
        attemps += 1
        if attemps < maximumatemps:
            print(f"PIN not correct. {maximumatemps - attemps} remaining attempts.")
        else:
            print(f"You have exceeded the maximum of {maximumatemps} login attempts. Account locked.")

#q5c

PIN_NUMBER = "1234"
balance = 1000
attemps = 0
maximumatemps = 3
is_active = True
username = "meghowal"
password = "1234"

input_username = input("Enter username: ")
input_password = input("Enter password: ")
if input_username == username and input_password == password:
    print("Login successful")
if is_active == False :
 print ("your account is locked")


while attemps < maximumatemps:
    INPUT_PIN = input("Enter your PIN: ")
    if INPUT_PIN == PIN_NUMBER:
        print("PIN accepted. Welcome!")

        input_withdraw_amount = int(input("Enter the amount to withdraw: "))
        if input_withdraw_amount <= balance and input_withdraw_amount > 500:
            balance -= input_withdraw_amount
            print(f"Withdrawal successful. Remaining balance: {balance}")
        elif input_withdraw_amount > balance:
            print("Insufficient balance")
        elif input_withdraw_amount <= 500:
            print("Minimum withdrawal amount is greater than 500")
        break

    else:
        attemps += 1
        if attemps < maximumatemps:
            print(f"PIN not correct. {maximumatemps - attemps} remaining attempts.")
           # sis_active = True

        else:
            print(f"You have exceeded the maximum of {maximumatemps} login attempts. Account locked.")
           # sis_active = False



#aiiiiiii

correct_username = "meghowal"
correct_password = 1234
is_active = True
pinNumber = 1234
balance = 1000
attempts = 3

if not is_active:
    print("Account is disabled.")
else:
    # Ask for login credentials
    user_input = input("Enter username: ")
    try:
        pass_input = int(input("Enter password: "))
    except ValueError:
        pass_input = None  # Handles non-numeric input

    # Validate Login
    if user_input == correct_username and pass_input == correct_password:
        print(f"Login successful! Welcome, {user_input}.")

        # --- ATM Section (Proceeds only if Login is successful) ---
        while attempts > 0:
            try:
                entered_pin = int(input(f"Enter ATM PIN ({attempts} attempts left): "))

                if entered_pin == pinNumber:
                    print("PIN correct.")

                    # Withdrawal Logic
                    request = int(input("Enter amount to withdraw: "))
                    if request > balance:
                        print("Insufficient balance.")
                    elif request <= 500:
                        print("Requested amount must be greater than 500.")
                    else:
                        balance -= request
                        print(f"Successful withdrawal! Remaining balance: {balance}")
                    break # Exit loop after successful transaction

                else:
                    attempts -= 1
                    if attempts > 0:
                        print(f"Wrong pin. Attempts remaining: {attempts}")
                    else:
                        print("Card blocked!")

            except ValueError:
                print("Invalid input. Please enter numbers only.")
                attempts -= 1

    elif user_input == correct_username:
        print("Incorrect password. Try again.")
    else:
        print("User not found.")

#6a1
for i in range(1, 21):
    print(i)

#6a2
for i in range(1, 11):
    print(f"7 x {i} = {7 * i}")

#6a3
total = 0
for i in range(1, 101):
    total += i
print("The sum is:", total)

#6a4
for i in range(2, 51, 2):
    print(i)

#6a5
fruits = ['apple', 'banana', 'cherry', 'mango', 'grape']

for index, fruit in enumerate(fruits, start=1):
    print(f"{index}. {fruit}")
